# Generated by Django 4.1 on 2022-08-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.CharField(default='Список подписанных', max_length=30, verbose_name='Подписанные пользователи'),
        ),
        migrations.AlterField(
            model_name='event',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examer.exam', verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examer.group', verbose_name='Поток'),
        ),
    ]
