# Generated by Django 4.1 on 2022-08-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examer', '0004_telegramuser_usersubscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscriptions',
            options={'verbose_name': 'Подписки Пользователей', 'verbose_name_plural': 'Подписки Пользователей'},
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя Пользователя'),
        ),
        migrations.CreateModel(
            name='UserExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examer.event', verbose_name='Проводимый экзамен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='examer.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Экзамены Пользователей',
                'verbose_name_plural': 'Экзамены Пользователей',
            },
        ),
    ]
